---
- name: install apache
  become: true
  yum:
    name: httpd
    state: present

- name: install git
  become: true
  yum:
    name: git
    state: present

- name: clone tooling repo
  become: true
  git:
    repo: https://github.com/toritsejuFO/tooling.git
    dest: /var/www/html
    force: yes

- name: copy html content to one level up
  become: true
  command: cp -r /var/www/html/html/ /var/www/

- name: start httpd service
  become: true
  service:
    name: httpd
    state: started

- name: recursively remove /var/www/html/html/ directory
  become: true
  file:
    path: /var/www/html
    state: absent
